package org.tavall.hytale.resourcegame.persistence.postgres;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.sql.DataSource;

/**
 * Creates required kingdom tables for profile, game state, and future unit metadata.
 */
public class PostgresSchemaLifecycle {

  private final DataSource dataSource;

  public PostgresSchemaLifecycle(DataSource dataSource) {
    this.dataSource = dataSource;
  }

  public void ensureSchema() {
    try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
      statement.execute("""
          CREATE TABLE IF NOT EXISTS player_profile (
            internal_player_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            player_uuid VARCHAR(64) NOT NULL UNIQUE,
            player_name VARCHAR(128) NOT NULL,
            timezone VARCHAR(80) NOT NULL,
            transformed_ip VARCHAR(255) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            last_seen_at TIMESTAMP NOT NULL
          )
          """);
      statement.execute("""
          CREATE TABLE IF NOT EXISTS player_game_state (
            profile_id BIGINT PRIMARY KEY,
            castle_id VARCHAR(64),
            castle_world VARCHAR(120),
            castle_x DOUBLE PRECISION,
            castle_y DOUBLE PRECISION,
            castle_z DOUBLE PRECISION,
            citizen_count INT NOT NULL,
            troop_count INT NOT NULL,
            food INT NOT NULL,
            wood INT NOT NULL,
            iron INT NOT NULL,
            current_interior_world VARCHAR(120),
            population_metadata_json TEXT,
            aging_cadence VARCHAR(80),
            last_aging_evaluation TIMESTAMP,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_player_profile FOREIGN KEY(profile_id) REFERENCES player_profile(internal_player_id)
          )
          """);
      statement.execute("""
          CREATE TABLE IF NOT EXISTS player_population_unit (
            profile_id BIGINT NOT NULL,
            unit_id VARCHAR(64) NOT NULL,
            role VARCHAR(32) NOT NULL,
            job VARCHAR(32) NOT NULL,
            strength INT NOT NULL,
            discipline INT NOT NULL,
            craft INT NOT NULL,
            morale INT NOT NULL,
            birth_at TIMESTAMP NOT NULL,
            last_role_shift_at TIMESTAMP NOT NULL,
            PRIMARY KEY(profile_id, unit_id),
            CONSTRAINT fk_population_profile FOREIGN KEY(profile_id) REFERENCES player_profile(internal_player_id)
          )
          """);
    } catch (SQLException exception) {
      throw new IllegalStateException("Unable to initialize postgres schema", exception);
    }
  }
}
